### ISSUE TITLE
WindowsError: [Error 216] This version of %1 is not compatible

### ISSUE THREAD

**Issue by JerryYangJin** [atom/libchromiumcontent#101]
Hi, 
I was trying to build libchromiumcontent on my windows 7 32-bit Enterprise Edition. I have python 2.7 and Visual Studio 2013 Express installed.

When I tried update script, i got below error, please kindly help, thank you!

```sh
C:\xxx\libchromiumcontent>python script/update -t ia32
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
...........
Extracting...
Traceback (most recent call last):
  File "script/update", line 213, in <module>
    sys.exit(main())
  File "script/update", line 32, in main
    download_source_tarball(version)
  File "script/update", line 86, in download_source_tarball
    tar_xf(xz_name)
  File "script/update", line 96, in tar_xf
    subprocess.call([xz(), '-dqk', filename])
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 216] This version of %1 is not compatible with the version
of Windows you're running. Check your computer's system information to see wheth
er you need a x86 (32-bit) or x64 (64-bit) version of the program, and then cont
act the software publisher
```

**Comment by zcbenz** [comment]
libchromiumcontent can only be built on 64bit Windows, even if you are building for 32bit target.
