### ISSUE TITLE
Mac OS X 10.10.2 - script/update fail

### ISSUE THREAD

**Issue by JerryYangJin** [atom/libchromiumcontent#108]
Hi, 

I was trying to build libchromiumcontent in Yosmite 10.10.2, but failed at script/update step, below are the message, please advise, thanks!

```sh
script/update -t x64
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Extracting...
Traceback (most recent call last):
  File "script/update", line 213, in <module>
    sys.exit(main())
  File "script/update", line 32, in main
    download_source_tarball(version)
  File "script/update", line 86, in download_source_tarball
    tar_xf(xz_name)
  File "script/update", line 98, in tar_xf
    tar = tarfile.open(tar_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1660, in open
    return func(name, "r", fileobj, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1722, in gzopen
    fileobj = bltn_open(name, mode + "b")
IOError: [Errno 2] No such file or directory: 'chromium-41.0.2272.76.tar'
```

**Comment by JerryYangJin** [comment]
the xz included can't be used on my Mac, replacing the xz and it's lib then the update script will pass
