### ISSUE TITLE
script Update for arm failing continously

### ISSUE THREAD

**Issue by sdinesh86** [atom/libchromiumcontent#145]
Hello,

I am trying to update the script in order to build for arm arch, but it is been failing at the update while downloading the tarball. below is the details log of the error

"Traceback (most recent call last):
  File "script/update", line 227, in <module>
    sys.exit(main())
  File "script/update", line 32, in main
    download_source_tarball(version)
  File "script/update", line 78, in download_source_tarball
    chunk = u.read(1024*1024)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 567, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
"
I tried downloading the file and putting it in the folder, but it doesnt seem to work can anyone please help me on this.

Thanks

**Comment by zcbenz** [comment]
This is caused by bad networking condition, you can probably switch to a faster internet.
