### ISSUE TITLE
El Capitan build error

### ISSUE THREAD

**Issue by puryfury** [atom/libchromiumcontent#173]
ehh...
I tried to build libchromiumcontent but it failed to build with following errors.
anybody can help?

```
$ ./script/build
ninja: Entering directory `vendor/chromium/src/out/Release'
[979/12451] OBJCXX obj/base/mac/base.mac_util.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/base/mac/base.mac_util.o.d -DU_COMBINED_IMPLEMENTATION -DUNISTR_FROM_CHAR_EXPLICIT= -DUNISTR_FROM_STRING_EXPLICIT= -DU_NO_DEFAULT_INCLUDE_UTF_HEADERS=0 -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=247874-1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DDONT_EMBED_BUILD_METADATA -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_BROWSER_SPELLCHECKER=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DSAFE_BROWSING_SERVICE -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DBASE_IMPLEMENTATION -DSYSTEM_NATIVE_UTF8 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../.. -isysroot /Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -O2 -gdwarf-2 -fvisibility=hidden -Werror -Wnewline-eof -mmacosx-version-min=10.8 -arch x86_64 -Wno-deprecated-declarations -Wall -Wendif-labels -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wpartial-availability -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-bitfield-width -Wexit-time-destructors -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -Xclang -load -Xclang /Volumes/coffee/projects/libchromiumcontent/vendor/chromium/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -fcolor-diagnostics -fno-strict-aliasing -Wobjc-missing-property-synthesis -fobjc-call-cxx-cdtors  -c ../../base/mac/mac_util.mm -o obj/base/mac/base.mac_util.o
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:499:3: error: redefinition of enumerator 'NSPressureBehaviorUnknown'
  NSPressureBehaviorUnknown = -1,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:187:5: note: previous definition is here
    NSPressureBehaviorUnknown = -1,
    ^
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:500:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryDefault'
  NSPressureBehaviorPrimaryDefault = 0,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:190:5: note: previous definition is here
    NSPressureBehaviorPrimaryDefault = 0,
    ^
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:501:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryClick'
  NSPressureBehaviorPrimaryClick = 1,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:198:5: note: previous definition is here
    NSPressureBehaviorPrimaryClick = 1,
    ^
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:502:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryGeneric'
  NSPressureBehaviorPrimaryGeneric = 2,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:206:5: note: previous definition is here
    NSPressureBehaviorPrimaryGeneric = 2,
    ^
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:503:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryAccelerator'
  NSPressureBehaviorPrimaryAccelerator = 3,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:214:5: note: previous definition is here
    NSPressureBehaviorPrimaryAccelerator = 3,
    ^
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:504:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryDeepClick'
  NSPressureBehaviorPrimaryDeepClick = 5,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:222:5: note: previous definition is here
    NSPressureBehaviorPrimaryDeepClick = 5,
    ^
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:505:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryDeepDrag'
  NSPressureBehaviorPrimaryDeepDrag = 6
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:230:5: note: previous definition is here
    NSPressureBehaviorPrimaryDeepDrag = 6,
    ^
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:498:1: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
enum {
^
../../base/mac/sdk_forward_declarations.h:507:19: error: typedef redefinition with different types ('NSInteger' (aka 'long') vs 'NSPressureBehavior')
typedef NSInteger NSPressureBehavior;
                  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:186:28: note: previous definition is here
typedef NS_ENUM(NSInteger, NSPressureBehavior) {
                           ^
In file included from ../../base/mac/mac_util.mm:23:
../../base/mac/sdk_forward_declarations.h:509:1: error: duplicate interface definition for class 'NSPressureConfiguration'
@interface NSPressureConfiguration : NSObject
^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPressureConfiguration.h:16:12: note: previous definition is here
@interface NSPressureConfiguration : NSObject {
           ^
10 errors generated.
[979/12451] OBJCXX obj/base/mac/base.sdk_forward_declarations.o
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/base/mac/base.sdk_forward_declarations.o.d -DU_COMBINED_IMPLEMENTATION -DUNISTR_FROM_CHAR_EXPLICIT= -DUNISTR_FROM_STRING_EXPLICIT= -DU_NO_DEFAULT_INCLUDE_UTF_HEADERS=0 -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=247874-1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DDONT_EMBED_BUILD_METADATA -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_BROWSER_SPELLCHECKER=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_WIFI_BOOTSTRAPPING=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DSAFE_BROWSING_SERVICE -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DBASE_IMPLEMENTATION -DSYSTEM_NATIVE_UTF8 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../.. -isysroot /Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -O2 -gdwarf-2 -fvisibility=hidden -Werror -Wnewline-eof -mmacosx-version-min=10.8 -arch x86_64 -Wno-deprecated-declarations -Wall -Wendif-labels -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wpartial-availability -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-bitfield-width -Wexit-time-destructors -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -Xclang -load -Xclang /Volumes/coffee/projects/libchromiumcontent/vendor/chromium/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -fcolor-diagnostics -fno-strict-aliasing -Wobjc-missing-property-synthesis -fobjc-call-cxx-cdtors  -c ../../base/mac/sdk_forward_declarations.mm -o obj/base/mac/base.sdk_forward_declarations.o
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:499:3: error: redefinition of enumerator 'NSPressureBehaviorUnknown'
  NSPressureBehaviorUnknown = -1,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:187:5: note: previous definition is here
    NSPressureBehaviorUnknown = -1,
    ^
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:500:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryDefault'
  NSPressureBehaviorPrimaryDefault = 0,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:190:5: note: previous definition is here
    NSPressureBehaviorPrimaryDefault = 0,
    ^
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:501:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryClick'
  NSPressureBehaviorPrimaryClick = 1,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:198:5: note: previous definition is here
    NSPressureBehaviorPrimaryClick = 1,
    ^
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:502:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryGeneric'
  NSPressureBehaviorPrimaryGeneric = 2,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:206:5: note: previous definition is here
    NSPressureBehaviorPrimaryGeneric = 2,
    ^
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:503:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryAccelerator'
  NSPressureBehaviorPrimaryAccelerator = 3,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:214:5: note: previous definition is here
    NSPressureBehaviorPrimaryAccelerator = 3,
    ^
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:504:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryDeepClick'
  NSPressureBehaviorPrimaryDeepClick = 5,
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:222:5: note: previous definition is here
    NSPressureBehaviorPrimaryDeepClick = 5,
    ^
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:505:3: error: redefinition of enumerator 'NSPressureBehaviorPrimaryDeepDrag'
  NSPressureBehaviorPrimaryDeepDrag = 6
  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:230:5: note: previous definition is here
    NSPressureBehaviorPrimaryDeepDrag = 6,
    ^
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:498:1: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
enum {
^
../../base/mac/sdk_forward_declarations.h:507:19: error: typedef redefinition with different types ('NSInteger' (aka 'long') vs 'NSPressureBehavior')
typedef NSInteger NSPressureBehavior;
                  ^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:186:28: note: previous definition is here
typedef NS_ENUM(NSInteger, NSPressureBehavior) {
                           ^
In file included from ../../base/mac/sdk_forward_declarations.mm:5:
../../base/mac/sdk_forward_declarations.h:509:1: error: duplicate interface definition for class 'NSPressureConfiguration'
@interface NSPressureConfiguration : NSObject
^
/Applications/Developers/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPressureConfiguration.h:16:12: note: previous definition is here
@interface NSPressureConfiguration : NSObject {
           ^
10 errors generated.
[979/12451] OBJCXX obj/base/mac/base.scoped_sending_event.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./script/build", line 45, in <module>
    sys.exit(main())
  File "./script/build", line 33, in main
    subprocess.check_call([NINJA, '-C', config_dir] + TARGETS)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Volumes/coffee/projects/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'vendor/chromium/src/out/Release', 'chromiumcontent_all']' returned non-zero exit status 1
```

**Comment by zcbenz** [comment]
Building libchromiumcontent requires Xcode 6.4 and OS X 10.10 SDK. We will support Xcode 7 and OS X 10.11 SDK once we upgraded to a more recent Chrome version.

**Comment by rsms** [comment]
@zcbenz Is there a way to tell `script/build` (ninja, really) to use a certain version of xcodebuild and SDK?
