### ISSUE TITLE
re-running script/bootstrap after failure in src/third_party/binutils/download.py appears to succeed

### ISSUE THREAD

**Issue by ceeeKay** [atom/libchromiumcontent#59]
```
[...]
________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-clang-format -s src/third_party/clang_format/bin/win/clang-format.exe.sha1' in '/home/user/libchromiumcontent/vendor/chromium'
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s src/third_party/clang_format/bin/mac/clang-format.sha1' in '/home/user/libchromiumcontent/vendor/chromium'
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s src/third_party/clang_format/bin/linux/clang-format.sha1' in '/home/user/libchromiumcontent/vendor/chromium'
________ running '/usr/bin/python src/third_party/binutils/download.py' in '/home/user/libchromiumcontent/vendor/chromium'
Traceback (most recent call last):
  File "src/third_party/binutils/download.py", line 118, in <module>
    sys.exit(main(sys.argv))
  File "src/third_party/binutils/download.py", line 104, in main
    arch = GetArch()
  File "src/third_party/binutils/download.py", line 51, in GetArch
    return subprocess.check_output(['python', DETECT_HOST_ARCH]).strip()
AttributeError: 'module' object has no attribute 'check_output'
Error: Command /usr/bin/python src/third_party/binutils/download.py returned non-zero exit status 1 in /home/user/libchromiumcontent/vendor/chromium

$ script/bootstrap
Synchronizing submodule url for 'vendor/python-patch'
________ running 'svn update /home/user/libchromiumcontent/vendor/chromium/36.0.1985.125 --non-interactive --accept postpone --ignore-externals' in '/home/user/libchromiumcontent/vendor/chromium'
Updating '36.0.1985.125':
At revision 286312.
Syncing projects: 100% (98/98), done.                                                               
Updating projects from gyp files...
Running build/landmines.py...
```
My system has Python 2.6 which I believe is likely the source of the error, (as from what I can tell subprocess.check_output() was introduced in 2.7), but if I re-run the command (without a git clean) it doesn't appear to have an error (rather than running up against the same error).

Maybe this error is non-fatal, maybe it isn't, but the scripts seem like they should make that clearer.

**Comment by zcbenz** [comment]
Recent versions should have fixed this problem.
